name: ocr
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '2.19.0-146.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # flutter_localizations:
  flutter_localizations:
    sdk: flutter  


  cupertino_icons: ^1.0.2
  #for responsive UI
  flutter_screenutil: ^5.6.0
  # bloc for State Management
  flutter_bloc: ^8.1.1
  #Google ML Kit Text Recognition 
  google_mlkit_text_recognition: ^0.5.0
  #Image Picker
  image_picker: ^0.8.6
  #Image Cropper
  image_cropper: ^3.0.1
  # shared preferences 
  shared_preferences: ^2.0.16
  #onBoarding Page
  liquid_swipe: ^3.0.0
  #Share 
  share_plus: ^6.3.0
  #
  url_launcher: ^6.1.9
  rename: ^2.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo/
    - assets/images/
    - assets/images/onboarding/
    - assets/icons/
    - assets/lang/


     
 